### ISSUE TITLE
Generate content pages from Strapi data

### ISSUE THREAD

**Issue by lakaniemi** [Tietokilta/tikweb-frontend#11]
## Description

See Gatsby [docs](https://www.gatsbyjs.com/docs/tutorial/part-seven/). Create a page template for content pages and do some gatsby magic so we can generate pages based on data from Strapi.

# Tasks

- [ ] See if `gatsby-node.js` can be converted to TypeScript, so we can get type support there as well
- [ ] Consider parents when creating slugs, so that subpage `y` of page `x` would be `x/y` and not just `y`
- [ ] Rendering logic for Dynamic Zone components

**Comment by PurkkaKoodari** [comment]
Done in #26
